//GET  ALL PRODUCT CLIENT AND ADMIN USER
export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_Fail = "GET_PRODUCTS_Fail";
// DELETE ONE PRODUCT ADMIN USER
export const DELETE_PRODUCT = "DELETE_PRODUCT";
// GET ONE PRODUCT BY ID
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_Fail = "GET_PRODUCT_Fail";
export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
// POST PRODUCT
export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_FAILD = "POST_PRODUCT_FAILD";
// EDIT PRODUCT
export const EDIT_PRODUCT = "EDIT_PRODUCT";

// SEARCH PRODUCT
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const GET_SEARCHED = "GET_SEARCHED";
